Update readme
layer5io/meet pull request #2
Opened 2020-10-21 11:47 UTC by chandrashritii

Signed-off-by: Shriti <shritichan@gmail.com>

**Description**

This PR fixes https://github.com/layer5io/layer5/issues/771

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-10-21 12:08 UTC, leecalcote requested changes
Looks good save for the part where the original meeting link goes missing. To ease troubleshooting and housekeeping, it would be good to retain the zoom.us links for reference.

2020-10-21 14:29 UTC, chandrashritii commented
Added zoom links

2020-10-21 15:52 UTC, leecalcote reviewed
Zoom links. 👍 

But lost the convenience of clickable hyperlinks.

2020-10-24 10:10 UTC, leecalcote approved these changes

2020-10-24 10:10 UTC, merged